[anchors]
    [anchors.Dagesh]
    glyphs = [ "hebrew point dagesh or mapiq", ]
    [anchors.HighNiqqud]
    glyphs = [ "hebrew point holam",
               "hebrew point holam haser for vav",
               "hebrew point shin dot",
               "hebrew point sin dot",
             ]
    [anchors.LowWideNiqqud]
    glyphs = [ "hebrew point hataf patah",
               "hebrew point hataf qamats",
               "hebrew point hataf segol",
             ]
    [anchors.LowNarrowNiqqud]
    glyphs = [ "hebrew point hiriq",
               "hebrew point meteg",
               "hebrew point patah",
               "hebrew point qamats",
               "hebrew point qamats qatan",
               "hebrew point qubuts",
               "hebrew point segol",
               "hebrew point sheva",
               "hebrew point tsere",
             ]
    [anchors.Rafe]
    glyphs = [ "hebrew point rafe", ]

# Enter data here to overide the default settings for anchor placement.
# Note that these are highly volatile, and subjective.  If a glyph
# changes, the values below are likely to change as well.
# However, without gross changes to the letterform's shape, these values
# should remain a very good estimate of the positioning.

[hebrew letter ayin.corrections]
    LowNarrowNiqqud = [440, 0]
    LowWideNiqqud   = [470, 0]
[hebrew letter dalet.corrections]
    LowNarrowNiqqud = [510, 0]
    LowWideNiqqud   = [480, 0]
[hebrew letter he.corrections]
    LowNarrowNiqqud = [320, 0]
    LowWideNiqqud   = [320, 0]
[hebrew letter final kaf.corrections]
    LowNarrowNiqqud = [300, 360]
    LowWideNiqqud   = [300, 360]
[hebrew letter lamed.corrections]
    LowNarrowNiqqud = [280, 0]
    LowWideNiqqud   = [280, 0]
[hebrew letter nun.corrections]
    LowNarrowNiqqud = [210, 0]
    LowWideNiqqud   = [210, 0]
[hebrew letter qof.corrections]
    LowNarrowNiqqud = [330, 0]
    LowWideNiqqud   = [370, 0]
[hebrew letter resh.corrections]
    LowNarrowNiqqud = [470, 0]
    LowWideNiqqud   = [430, 0]
[hebrew letter tav.corrections]
    LowNarrowNiqqud = [425, 0]
    LowWideNiqqud   = [425, 0]
[hebrew letter vav.corrections]
    LowNarrowNiqqud = [220, 0]
    LowWideNiqqud   = [200, 0]
[hebrew letter yod.corrections]
    LowNarrowNiqqud = [180, 0]
    LowWideNiqqud   = [180, 0]
[hebrew letter zayin.corrections]
    LowNarrowNiqqud = [155, 0]
    LowWideNiqqud   = [155, 0]

[directories]
letters     = "./Draft Material/Letterforms"
punctuation = "./Draft Material/Punctuation"
niqqudot    = "./Draft Material/Niqqudot"

# Used to create lookup tables.  These simply set up the tables, but don't
# deal with glyph placement.  These probably aren't the droids you're looking
# for....  Check out `<glyphname>.corrections` for alignment data.
[[lookups]]
name  = "'mark' Low Narrow Niqqud in Hebrew lookup 0"
type  = "gpos_mark2base"
flags = "right_to_left"

    [[lookups.features]]
    name = "mark"
        [[lookups.features.scripts]]
        name  = "DFLT"
        langs = ["dflt"]
        [[lookups.features.scripts]]
        name  = "hebr"
        langs = ["dflt"]

    [[lookups.subtables]]
    name      = "'mark' Low Narrow Niqqud in Hebrew lookup 0-1"
    mark name = "LowNarrowNiqqud"

[[lookups]]
name  = "'mark' Low Wide Niqqud in Hebrew lookup 1"
type  = "gpos_mark2base"
flags = "right_to_left"

    [[lookups.features]]
    name = "mark"
        [[lookups.features.scripts]]
        name  = "DFLT"
        langs = ["dflt"]
        [[lookups.features.scripts]]
        name  = "hebr"
        langs = ["dflt"]

    [[lookups.subtables]]
    name      = "'mark' Low Wide Niqqud in Hebrew lookup 1-1"
    mark name = "LowWideNiqqud"

[[lookups]]
name  = "'mark' High Niqqud in Hebrew lookup 2"
type  = "gpos_mark2base"
flags = "right_to_left"

    [[lookups.features]]
    name = "mark"
        [[lookups.features.scripts]]
        name  = "DFLT"
        langs = ["dflt"]
        [[lookups.features.scripts]]
        name  = "hebr"
        langs = ["dflt"]

    [[lookups.subtables]]
    name      = "'mark' High Niqqud in Hebrew lookup 2-1"
    mark name = "HighNiqqud"

[[lookups]]
name  = "'mark' Dagesh in Hebrew lookup 3"
type  = "gpos_mark2base"
flags = "right_to_left"

    [[lookups.features]]
    name = "mark"
        [[lookups.features.scripts]]
        name  = "DFLT"
        langs = ["dflt"]
        [[lookups.features.scripts]]
        name  = "hebr"
        langs = ["dflt"]

    [[lookups.subtables]]
    name      = "'mark' Dagesh in Hebrew lookup 3-1"
    mark name = "Dagesh"

[[lookups]]
name  = "'mark' Rafe in Hebrew lookup 4"
type  = "gpos_mark2base"
flags = "right_to_left"

    [[lookups.features]]
    name = "mark"
        [[lookups.features.scripts]]
        name  = "DFLT"
        langs = ["dflt"]
        [[lookups.features.scripts]]
        name  = "hebr"
        langs = ["dflt"]

    [[lookups.subtables]]
    name      = "'mark' Rafe in Hebrew lookup 4-1"
    mark name = "Rafe"

[specs]
# Font name attributes
family name  = "Mazon Hebrew"
font name    = "MazonHebrew-Regular"
full name    = "Mazon Hebrew Regular"
weight       = "Regular"

# `real em` is as reported and rounded by `makefont.py -m`.  `fontforge em` is
# what would go in the Font Info dialog.
# Note that `descent` and `ascent` must (should?) add up to `fontforge em`.
real em      = 650
fontforge em = 1000
descent      = 247
ascent       = 753

encoding     = "UnicodeBmp"
version      = "v0.2"

    [specs.spaces]
    # The key is the unicode name of a space character.  The value is a float
    # representing the percentage of `specs.real em` that the space should
    # take up.  Changing these will change the width of the space glyphs.
    space                 = 0.4
    no-break space        = 0.4
    en quad               = 0.5
    em quad               = 1.0
    en space              = 0.5
    em space              = 1.0
    three-per-em space    = 0.3333
    four-per-em space     = 0.25
    six-per-em space      = 0.1667
    # figure space = ?
    # punctuation space = ?
    thin space            = 0.2
    hair space            = 0.1
    zero width space      = 0.0
    zero width non-joiner = 0.0
    zero width joiner     = 0.0
    # Not spaces, but might as well go here
    left-to-right mark    = 0.0
    right-to-left mark    = 0.0
